In [1]:
import pickle
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving clf.pkl to clf.pkl
Saving ohe_embarked.pkl to ohe_embarked.pkl
Saving ohe_sex.pkl to ohe_sex.pkl


In [3]:
with open("clf.pkl", "rb") as f:
    clf = pickle.load(f)

with open("ohe_sex.pkl", "rb") as f:
    ohe_sex = pickle.load(f)

with open("ohe_embarked.pkl", "rb") as f:
    ohe_embarked = pickle.load(f)


In [5]:
#assume user input
# PClass/Gender/Age/SibSp/Parch/Fare/Embarked
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [7]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [8]:
test_input_sex

array([[0., 1.]])

In [9]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [10]:
test_input_embarked

array([[0., 0., 1.]])

In [12]:
test_input_age = test_input[:,2].reshape(1,1)

In [13]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_embarked,test_input_sex),axis = 1)

In [15]:
test_input_transformed.shape

(1, 10)

In [16]:
clf.predict(test_input_transformed)

array([1])